#!/bin/sh

# Set user and system paths for resources and keymaps.
userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
colorscheme=$XDG_CONFIG_HOME/X11/colorschemes/cyberpunk

# Merge defaults and system files.
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -I$XDG_CONFIG_HOME/X11/ -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Man Fix
export MAN_DISABLE_SECCOMP=1

# XRandr Nvidia Fix
# Comment this line if you don't use prop. NVIDIA driver
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

# GnomeKeyring i3 Fix
dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# Start i3
exec i3 -V
